language: python
sudo: false
os:
  - linux
python:
  - "2.7"
addons:
  # numpy is hard to install on travis!
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
env:
    - REQUIREMENTS=requirements_stable.txt
    - REQUIREMENTS=requirements.txt
before_install:
  - pip install -U pip
# command to install dependencies
install: 
  - wget -q http://download.pytorch.org/whl/cu75/torch-0.1.11.post5-cp27-none-linux_x86_64.whl
  - travis_retry pip install torch-0.1.11.post5-cp27-none-linux_x86_64.whl
  - travis_wait travis_retry pip install -r $REQUIREMENTS
# command to run tests
script: python -m convis.tests
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
